version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: 
      - base-McFit/McFit/docs/requirements.txt
    - extra_requirements
      - progress.bar
      - corner


sphinx:
  configuration: base-McFit/McFit/docs/source/conf.py
