[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "McFit"
authors = [{name = "Andrés Cook", email = "andcook5@gmail.com"}]
dynamic = ["version", "description"]
